In [1]:
from torch_geometric.loader import DataLoader
from torch_geometric import seed_everything
from imports.TrainModel import TrainModel
seed_everything(0)

from models.gcn import ya_1
model = ya_1().to('cuda')
model

#!rm ../data/contact_extraction2/{train,test,val}/processed/*

tm = TrainModel('/home/hussain/tactile/data/contact_extraction2/', model)

In [2]:
tm.train()

Epoch 0:   0%|                               | 0/407 [00:00<?, ?batch/s]/home/hussain/tactile/src/imports/TrainModel.py:53: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
/home/hussain/tactile/src/models/gcn.py:42: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data.x = F.sigmoid(self.conv1(torch.tensor(data.x.view(-1,1), dtype=torch.float32), data.edge_index) )#, data.edge_attr ))
/home/hussain/miniconda3/envs/tactile38/lib/python3.8/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/hussain/miniconda3/envs/tactile38/lib/python3.8/site-packages/torch/nn/modules/lo

KeyboardInterrupt: 

In [7]:
from pathlib import Path

p = '/home/hussain/tactile/data/contact_extraction2/'
Path(p)

PosixPath('/home/hussain/tactile/data/contact_extraction2')

In [2]:
import torch_geometric.transforms as T
train_data_aug = T.Compose([T.Cartesian(cat=False), T.RandomFlip(axis=0, p=0.3), T.RandomScale([0.95,0.999]) ])


In [3]:
from models.gcn import ya_1
model = ya_1().to('cuda')
model

ya_1(
  (conv1): GCNConv(1, 64)
  (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): GCNConv(64, 64)
  (bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): GCNConv(128, 512)
  (bn3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv4): GCNConv(512, 256)
  (bn4): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv5): GCNConv(256, 64)
  (bn5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv6): GCNConv(64, 32)
  (bn6): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv7): GCNConv(32, 16)
  (bn7): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv8): GCNConv(16, 2)
  (bn8): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc1): Linear(in_features=16, out_features=16, bias=True)
 

In [6]:
sample

DataBatch(x=[10197, 16], edge_index=[2, 326304], y=[6], pos=[10197, 3], edge_attr=[326304, 3], batch=[10197], ptr=[4])

In [16]:
" "

' '

In [4]:
sample = next(iter(tdloader)).to('cuda')
sample

DataBatch(x=[10197, 1], edge_index=[2, 326304], y=[6], pos=[10197, 3], edge_attr=[326304, 3], batch=[10197], ptr=[4])

In [5]:
model(train_data_aug(sample))

/home/hussain/tactile/src/models/gcn.py:42: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data.x = F.sigmoid(self.conv1(torch.tensor(data.x.view(-1,1), dtype=torch.float32), data.edge_index) )#, data.edge_attr ))
/home/hussain/miniconda3/envs/tactile38/lib/python3.8/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([[ 0.0682,  0.2231],
        [-0.1260,  0.5034],
        [ 0.1214,  0.2601]], device='cuda:0', grad_fn=<EluBackward0>)

In [ ]:
sample.x.view(-1, 1).shape

In [ ]:
sample.x.dtype

In [8]:
sample.y

tensor([ 3.4907e-02, -8.5496e-18], device='cuda:0', dtype=torch.float64)

In [ ]:
from torch_geometric.nn import SplineConv, voxel_grid, max_pool, max_pool_x

sconv = SplineConv(1, 64, dim=3, kernel_size=5)
sconv(sample.x.view(-1, 1), sample.edge_index, sample.edge_attr)

In [ ]:
torch.load('/home/hussain/data/event_based_sign_lang/test/processed/a/a_0000.pt')

In [ ]:
import torch

torch.cuda.is_available()

In [30]:
import torch
import torch_geometric as pyg
import numpy as np

pos = np.array(pos).astype(np.float32)
x = np.array([1, 1, 1, 1]).reshape(-1, 1).astype(np.float32)
edge_index = np.array([[0, 1], [1, 2], [2, 3]]).T

pos = torch.tensor(pos)
x = torch.tensor(x)
edge_index = torch.tensor(edge_index)
data = pyg.data.Data(x, edge_index, pos = pos)
pseudo = pyg.transforms.Cartesian()(data)

data

Data(x=[4, 1], edge_index=[2, 3], pos=[4, 2], edge_attr=[3, 2])

In [54]:
from torch_geometric.nn import GCNConv

gc = GCNConv(1, 1)
gc(data.x, data.edge_index)

tensor([[0.9291],
        [1.1216],
        [0.9291],
        [0.9291]], grad_fn=<AddBackward0>)

In [57]:
for p in gc.parameters():
    print(p)

Parameter containing:
tensor([0.], requires_grad=True)
Parameter containing:
tensor([[0.9291]], requires_grad=True)


In [65]:
from argparse import ArgumentParser

import torch
import torch.nn.functional as F
from torch import nn
from torch.optim import SGD
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision.transforms import Compose, Normalize, ToTensor
from tqdm import tqdm

from ignite.engine import create_supervised_evaluator, create_supervised_trainer, Events
from ignite.metrics import Accuracy, Loss
from ignite.utils import setup_logger


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x, dim=-1)


def get_data_loaders(train_batch_size, val_batch_size):
    data_transform = Compose([ToTensor(), Normalize((0.1307,), (0.3081,))])

    train_loader = DataLoader(
        MNIST(download=True, root=".", transform=data_transform, train=True), batch_size=train_batch_size, shuffle=True
    )

    val_loader = DataLoader(
        MNIST(download=False, root=".", transform=data_transform, train=False), batch_size=val_batch_size, shuffle=False
    )
    return train_loader, val_loader


def run(train_batch_size, val_batch_size, epochs, lr, momentum, log_interval):
    train_loader, val_loader = get_data_loaders(train_batch_size, val_batch_size)
    model = Net()
    device = "cpu"

    if torch.cuda.is_available():
        device = "cuda"

    model.to(device)  # Move model before creating optimizer
    optimizer = SGD(model.parameters(), lr=lr, momentum=momentum)
    criterion = nn.NLLLoss()
    trainer = create_supervised_trainer(model, optimizer, criterion, device=device)
    trainer.logger = setup_logger("trainer")

    val_metrics = {"accuracy": Accuracy(), "nll": Loss(criterion)}
    evaluator = create_supervised_evaluator(model, metrics=val_metrics, device=device)
    evaluator.logger = setup_logger("evaluator")

    pbar = tqdm(initial=0, leave=False, total=len(train_loader), desc=f"ITERATION - loss: {0:.2f}")

    @trainer.on(Events.ITERATION_COMPLETED(every=log_interval))
    def log_training_loss(engine):
        pbar.desc = f"ITERATION - loss: {engine.state.output:.2f}"
        pbar.update(log_interval)

    @trainer.on(Events.EPOCH_COMPLETED)
    def log_training_results(engine):
        pbar.refresh()
        evaluator.run(train_loader)
        metrics = evaluator.state.metrics
        avg_accuracy = metrics["accuracy"]
        avg_nll = metrics["nll"]
        tqdm.write(
            f"Training Results - Epoch: {engine.state.epoch} Avg accuracy: {avg_accuracy:.2f} Avg loss: {avg_nll:.2f}"
        )

    @trainer.on(Events.EPOCH_COMPLETED)
    def log_validation_results(engine):
        evaluator.run(val_loader)
        metrics = evaluator.state.metrics
        avg_accuracy = metrics["accuracy"]
        avg_nll = metrics["nll"]
        tqdm.write(
            f"Validation Results - Epoch: {engine.state.epoch} Avg accuracy: {avg_accuracy:.2f} Avg loss: {avg_nll:.2f}"
        )

        pbar.n = pbar.last_print_n = 0

    @trainer.on(Events.EPOCH_COMPLETED | Events.COMPLETED)
    def log_time(engine):
        tqdm.write(f"{trainer.last_event_name.name} took { trainer.state.times[trainer.last_event_name.name]} seconds")

    trainer.run(train_loader, max_epochs=epochs)
    pbar.close()


run(train_batch_size=10, val_batch_size=10, epochs=20, lr=0.01, momentum=0.5, log_interval=10)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw



ITERATION - loss: 0.00:   0%|                  | 0/6000 [00:00<?, ?it/s]

TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

In [62]:
pip install pytorch-ignite


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.1/264.1 kB 2.5 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.
